#!/bin/sh -e

test -z "$BUILD_VER" && BUILD_VER=1
test -z "$LABEL" && LABEL=linux-x86_64

# cd to the directory where this script exists.
cd "$(dirname "$0")"
. ./script-helper

get_version

if [ -z "$VERSION" ]; then
    echo "No version found"
    exit 1
fi

DIST_DIR=aria2-${VERSION}-${LABEL}-build${BUILD_VER}

mkdir "$DIST_DIR"
cp AUTHORS COPYING ChangeLog LICENSE.OpenSSL NEWS README README.rst README.html \
    linux-out/aria2c "$DIST_DIR"
tar -cJf "$DIST_DIR.tar.xz" "$DIST_DIR"
rm -rf "$DIST_DIR"